### ISSUE TITLE
Config does not respect user setting for Core/Export/TempFolder/Location

### ISSUE THREAD

**Issue by brucedg** [Sitecore/Sitecore-Instance-Manager#66] opened 2016-02-04 19:59 UTC
Even after app restart and checking this setting is in AdvancedSettings.xml - the application still writes to the root of the default drive - in this case triggering McAfee scanning which seems to stall the export

**Comment by SaintSkeeta** [comment] 2017-05-09 21:13
Just found that this is still happening in v1.5.
I attempted to export a website, and see in the logs that it always creates a temp location in my drive root (C:\).
It actually breaks the wizard when write/delete access fails in the temp location (removing files).
My only way to get around this is to not exclude anything from the export (so keep license.xml, temp folder etc.).... then the wizard will complete. You can then uncrack the zip, manually remove those things anyway, and rezip it.

**Comment by AlenPelin** [comment] 2017-05-10 01:31
The setting is respected, but there was a bug in implementation. When setting value is E:\Sitecore\temp then temp location is used as E:\{guid}, otherwise default OS temp location plus random folder name.

**Comment by SaintSkeeta** [comment] 2017-05-10 01:40
Ah ok.... so it's only using the drive that's specified.... yeah that's still blocking me.
My workaround above had some issues (zero byte files were created in place of empty folders in my zip....which caused issues in the site)..... pretty sure that's just for my workaround though.

**Comment by AlenPelin** [comment] 2017-05-10 01:41
I've fixed that. The change should be populated within 30 minutes.

**Comment by AlenPelin** [comment] 2017-05-10 02:18
Released as 1.5.0.64

@SaintSkeeta please confirm that the issue is solved on your side.

**Comment by AlenPelin** [comment] 2017-05-11 00:05
Did you try to grant Everyone role Full Access? If this doesn't help, please raise another issue as it is something different from this issue's subject.

**Comment by SaintSkeeta** [comment] 2017-06-07 18:20
OK....got it working....permissions were fine....but my license.xml had a ReadOnly flag on it....
So I fixed it up, and now I can properly exclude it in the export. :-)

**Comment by AlenPelin** [comment] 2017-06-07 22:57
Thanks for confirming.

**Closed** 2017-06-07 22:57 UTC
Labels: bug
