### ISSUE TITLE
Actions taken over a non sitecore instance throw error

### ISSUE THREAD

**Issue by IvanSheyenko** [Sitecore/Sitecore-Instance-Manager#335] opened 2019-12-11 20:34 UTC
1. install xp
2. expand installed environment 
3. right-click xconnect instance and select delete

Result:
error is thrown.

Expected result:
No errors. Deletion process is started

Check the same for all operations available in cotext menu.

**Comment by DmitryKolinchuk** [comment] 2020-04-15 14:41
The main reported issue is not reproduced due to the following fix:
[https://github.com/Sitecore/Sitecore-Instance-Manager/pull/413](https://github.com/Sitecore/Sitecore-Instance-Manager/pull/413)

As for adding the context menu with the "Delete" and "Reinstall instance" commands to the expander (where the Sitecore environment name is displayed), we discussed with @RomanChernyk  and @AndreyFilchenkov that it's a non-trivial task to implement this in a proper way (without crutches) since the "ListBox" control doesn't allow to add the needed functionality in the proper way using binding to "SitecoreEnvironment" entities in the "Expander" control.
Summarizing, we decided to close this issue.

**Closed by DmitryKolinchuk** 2020-04-15 14:41 UTC
Labels: bug
