### ISSUE TITLE
Something went wrong with Wizard logic on the last step of configuring SIM

### ISSUE THREAD

**Issue by ViacheslavAfanasyev** [Sitecore/Sitecore-Instance-Manager#362] opened 2020-01-30 15:57 UTC
1. Install QA version 1.6.0.465
2. Complete all steps on configuring SIM

On the last step, when click "Next" button" it fails with the error "Something went wrong with Wizard logic on the last step of configuring SIM"

![image](https://user-images.githubusercontent.com/9393016/73465525-810f6000-434e-11ea-9d59-d9b3794ec06f.png)

[logs.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/4134877/logs.zip)

**Comment by AlenPelin** [comment] 2020-02-02 11:14
The cause is some black magic that removed my merged PR from 'develop' branch commits chain.

**Comment by AlenPelin** [comment] 2020-02-02 11:17
It looks like my PR got reverted 


https://github.com/Sitecore/Sitecore-Instance-Manager/pull/251

**Closed** 2020-02-05 17:12 UTC
Labels: bug
