### ISSUE TITLE
SIM opens off screen

### ISSUE THREAD

**Issue by jasonbert** [Sitecore/Sitecore-Instance-Manager#59] opened 2016-01-11 16:56 UTC
This seems to happen a lot whenever I install SIM for the first time on a machine. It opens off screen with the wizard and it's impossible to get it onto the viewable screen area. Right now I'm struggling to find a way to get through the wizard as I can't find a way to get it on screen.

**Comment by AlenPelin** [comment] 2016-01-11 22:33
What is your OS, what is your monitors configuration schema ([    ] [    ]), what are your screens resolutions and what are scaling settings for monitors?

**Workaround:** shift+click the app icon in taskbar -> move -> use arrow keys to move it onto screen.

**Comment by sergeyshushlyapin** [comment] 2016-07-21 14:54
Is that what you're talking about?

![image](https://cloud.githubusercontent.com/assets/4719165/17027272/f10dade2-4f6b-11e6-9f98-c4f31264a581.png)

**Comment by AlenPelin** [comment] 2016-07-22 00:21
Nope. I was able to reproduce that with custom DPI - sometimes main window opens far away from screen boundaries and you have to shift+right click the icon in taskbar -> move screen option to get it back.

**Comment by sergeyshushlyapin** [comment] 2016-07-22 07:06
> the issue you are referring to is already fixed.

Is it released? I'm asking because the screenshot is from the latest version I installed yesterday.

**Comment by AlenPelin** [comment] 2016-07-22 07:42
@sergeyshushlyapin of course, but only in QA. http://dl.sitecore.net/updater

**Comment by jasonbert** [comment] 2016-07-22 07:50
I've done a video showing the issue (http://screencast-o-matic.com/watch/cDi3iHikx7).

Screens: 1 (laptop)
Screen resolution: 3840x2160
Scaling: 250%
OS: Windows 10

**Comment by ivanbuzyka** [comment] 2016-07-22 08:05
Just to let you know guys, I also get that SIM look with text not fitting into SIM window (as showed on the screenshot on top of this thread). It seems I also have latest version.

**Comment by AlenPelin** [comment] 2016-07-22 09:35
Last version looks like this:
![clipboarder 2016 07 22-007](https://cloud.githubusercontent.com/assets/2854666/17053059/787afb36-5043-11e6-9c04-678d1d509b1f.png)

**Comment by sergeyshushlyapin** [comment] 2016-07-22 09:38
I've got v1.4.0383 from [here](http://dl.sitecore.net/updater/sim/SIM.Tool.application) yesterday :)
Is the source valid?

**Comment by AlenPelin** [comment] 2016-07-24 23:44
The thread was cleaned up from unrelated comments (which relate to already fixed #80)

**Comment by AlenPelin** [comment] 2017-07-12 02:24
Should be fixed now.

**Closed by AlenPelin** 2017-07-12 02:24 UTC
Labels: bug
