### ISSUE TITLE
Backup fails if database doesn't exist

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#237] opened 2019-03-12 11:44 UTC
---------------------------
Sitecore Instance Manager
---------------------------
Backing up databases action failed with message: Database 'sc902_xdb.processing.tasks' does not exist. Make sure that the name is entered correctly.

BACKUP DATABASE is terminating abnormally.

You can find details in the log file. Would you like to open it?
---------------------------
OK   Cancel   
---------------------------

**Comment by DmitryKolinchuk** [comment] 2023-03-13 08:30
Should be a duplicate of [https://github.com/Sitecore/Sitecore-Instance-Manager/issues/222](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/222).

**Comment by DmitryKolinchuk** [comment] 2023-03-14 08:55
Closed since the backup functionality is deprecated (removed) for Sitecore 9+ instances.

**Closed by DmitryKolinchuk** 2023-03-14 08:55 UTC
