### ISSUE TITLE
Installing Sitecore Demo 1.4 using SIM 1.5

### ISSUE THREAD

**Issue by Tgriesmar** [Sitecore/Sitecore-Instance-Manager#223] opened 2018-03-08 13:25 UTC
**Description:**  
I can't install Sitecore.Demo anymore on my server, by using SIM 1.5.0.179
The package I want to install is "Demo 1.4 rev rev. 161229 611.zip"

**Scenario:**  
1.  Open SIM 1.5.0.179
2. Click on Install Instance
3. Select the product "Demo", Version 1.4, and revision 161229 611 click on Next

![image_2018-03-08_11 11 49_am](https://user-images.githubusercontent.com/37181883/37153327-a1555afc-22dc-11e8-84f0-8ddbd667f377.png)

4. On step 4, Select Sitecore Instance (8.2.0 ev16122)

![image_2018-03-08_11 40 28_am](https://user-images.githubusercontent.com/37181883/37153117-00eb1606-22dc-11e8-97a6-4d0dde831202.png)

5. On step 5, select the Demo Package 

![image_2018-03-08_11 41 01_am](https://user-images.githubusercontent.com/37181883/37153139-0ef8363e-22dc-11e8-99f4-75177c006189.png)

6. When I click on "Install", I get the following error : 

![image_2018-03-08_11 41 56_am](https://user-images.githubusercontent.com/37181883/37153172-1f8a89e8-22dc-11e8-9c8d-4dbe0984332f.png)

![image_2018-03-08_11 45 13_am](https://user-images.githubusercontent.com/37181883/37153176-2390ac0c-22dc-11e8-9c82-6572ecc5b9a9.png)

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Screenshots:**

**Attachments:**  

[2018-03-08.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1793294/2018-03-08.txt)

**Comment by AlenPelin** [comment] 2018-03-09 02:54
duplicate of #219

**Closed by AlenPelin** 2018-03-09 02:54 UTC

**Comment by Tgriesmar** [comment] 2018-03-09 10:30
This issue isn't resolved at all. The solution described in #219 doesn't work.

**Comment by AlenPelin** [comment] 2018-03-13 00:17
You can download the source code and debug.
