### ISSUE TITLE
SIM application publisher is unknown

### ISSUE THREAD

**Issue by AlexeyChigarkov** [Sitecore/Sitecore-Instance-Manager#739] opened 2023-08-02 12:21 UTC
The SIM application publisher is unknown. Therefore Windows SmartScreen does not allow to run it.

**Comment by DmitryKolinchuk** [comment] 2023-09-07 11:59
This is a duplicate of https://github.com/Sitecore/Sitecore-Instance-Manager/issues/738.

**Closed** 2023-09-29 11:59 UTC
Labels: bug
