### ISSUE TITLE
Improve error logging/reporting

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#261] opened 2019-08-01 13:37 UTC
When trying to install Sitecore 9 I get the following error when clicking Install:
![image](https://user-images.githubusercontent.com/12621581/62297805-86145500-b47a-11e9-947d-a7c47c5368d2.png)

The error does not bring any explanation of what is going wrong.

When debugging SIM I've found out that it fails on executing the following line:
`Import-Module SitecoreInstallFramework -RequiredVersion 2.1.0`

On my laptop this gives an error:
`Import-Module : File C:\Program Files\WindowsPowerShell\Modules\SitecoreInstallFramework\2.1.0\SitecoreInstallFramework.psm1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.`

However, this neither gets logged anywhere in the application log nor is shown to the user.

Let's ensure we log everything that is executed in PowerShell and show errors to the user if possible.

**Comment by RomanChernyk** [comment] 2019-08-02 10:54
One more place to improve is error reporting during the installation itself. When there is an error, it is shown like this:
![image](https://user-images.githubusercontent.com/12621581/62365342-866d2880-b52c-11e9-950c-a739a14c342b.png)

When I click ok and open the SIM log I do not get many details. For my specific case just `Command C:\Program Files\iis\Microsoft Web Deploy V3\msdeploy.exe returned a non-zero exit code - (-1)`

However, more information is available in the SIF log in the source folder. We should somehow notify the user that more information can be found there.

**Comment by IvanSheyenko** [comment] 2019-08-05 18:48
> When trying to install Sitecore 9 I get the following error when clicking Install:
> ![image](https://user-images.githubusercontent.com/12621581/62297805-86145500-b47a-11e9-947d-a7c47c5368d2.png)
> 
> The error does not bring any explanation of what is going wrong.
> 
> When debugging SIM I've found out that it fails on executing the following line:
> `Import-Module SitecoreInstallFramework -RequiredVersion 2.1.0`
> 
> On my laptop this gives an error:
> `Import-Module : File C:\Program Files\WindowsPowerShell\Modules\SitecoreInstallFramework\2.1.0\SitecoreInstallFramework.psm1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.`
> 
> However, this neither gets logged anywhere in the application log nor is shown to the user.
> 
> Let's ensure we log everything that is executed in PowerShell and show errors to the user if possible.

This appears to be a bug in the generated script. It should set execution policy before attempting to run it. 
Fixed.

**Comment by RomanChernyk** [comment] 2019-08-06 07:24
@IvanSheyenko 
>This appears to be a bug in the generated script. It should set execution policy before attempting to run it.
> Fixed.

Thanks! Still, do you think it makes sense to log the scripts we execute? Not the ones that are a SIF tasks but those we execute directly from our code?

**Comment by RomanChernyk** [comment] 2019-08-19 14:13
Log the whole PowerShell session in case of an error.

**Comment by IvanSheyenko** [comment] 2019-10-17 20:15
Found the root cause of the above-mentioned null reference. Fixed in #276. Proper error is reported now.

**Comment by RomanChernyk** [comment] 2019-10-22 14:55
Summary:
1. We should log PowerShell commands (non-sif related) that we execute
2. Add an additional message to error dialog that for Sitecore 9+ more info can be found in SIF logs located in the folder with Sitecore installation files.

**Comment by IvanSheyenko** [comment] 2019-10-30 21:17
1. No need for additional logging here. Errors related to Non-SIF PS are logged into SIM log. Powershell session, in this case, does not contain any additional output.
2. Done. If SIF task fails sif log location is opened from error dialog.

**Comment by RomanChernyk** [comment] 2019-10-31 08:06
@IvanSheyenko tested. Looks good.

**Comment by AndreyFilchenkov** [comment] 2019-11-03 18:40
I am ok with the changes.

**Closed by AndreyFilchenkov** 2019-11-03 18:40 UTC
Labels: bug
