### ISSUE TITLE
App window is positioned outside of user-visible area in high resolution screens

### ISSUE THREAD

**Issue by Jabestrada** [Sitecore/Sitecore-Instance-Manager#178] opened 2017-06-12 02:23 UTC
**Importance:**  
Normal (I have a workaround, but it would be nice to fix it)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version [1.4]
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
The issue is the user cannot use the tool because the app window's Left and Top coordinates are positioned outside of the screen's user-visible area.

**Scenario:**  
Launch SIM; app window is docked (and can be previewed) on the Windows Taskbar but doesn't appear to the user when clicked/activated. My 15" screen's resolution is set to 3840 x 2160 which is the default factory setting; running on Windows 10.

**Workaround:**  
1. Issue seems to be on WindowHelper.ShowDialog(); using System.Windows.SystemParameters.WorkArea instead of Screen.PrimaryScreen.WorkingArea did the trick of centering the app window, though I haven't tested in other screens or resolutions.

2. Adjusting screen resolution without changing source code might also work but wasn't tested.

**Attachments:**  
I've attached output values of the two approaches:

![primaryscreenworkingarea](https://user-images.githubusercontent.com/11704536/27016598-53e8701c-4f54-11e7-8ac1-bd5b3b70ed88.png)
![systemparametersworkarea](https://user-images.githubusercontent.com/11704536/27016599-562ba010-4f54-11e7-8c2b-b233bfdde66c.png)

**Comment by AlenPelin** [comment] 2017-07-12 02:03
Duplicate of #59

**Closed by AlenPelin** 2017-07-12 02:03 UTC

**Comment by AlenPelin** [comment] 2017-07-12 02:24
Should be fixed now.
