### ISSUE TITLE
Imported website doesn't work. ZIP export contains broken files/folders

### ISSUE THREAD

**Issue by ivanbuzyka** [Sitecore/Sitecore-Instance-Manager#158] opened 2017-04-19 11:06 UTC
**Importance:**  
 
Normal (I have a workaround, but it would be nice to fix it)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version [PUT HERE EXACT VERSION NUMBER]
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
During the website export, some folders are packaged in a wierd way, so they end saved as files with no extension but not as folders. See screenshot of the export zip content as an example: https://db.tt/kb8Hyuk2Gf 

**Scenario:**  
1.  Use latest prod. version of SIM and export a website
2.  Import that export
3. Try to open the Sitecore backend

The problem: there is, for example, an IO exception related to creating of "upload" folder in the website root. See a screenshot here: https://db.tt/KgremxrU8f

**Comment by AlenPelin** [comment] 2017-04-19 23:28
Duplicate of #150

**Comment by ivanbuzyka** [comment] 2017-04-20 09:08
It looks a bit different from #150 , that is not just about web.config

**Comment by SaintSkeeta** [comment] 2017-05-10 21:43
I had this issue when unzipping/zipping the exported zip manually (I was trying to workaround a permissions issue I was having when excluding things from the export - see comments in #66 ).
I just tested a export (nothing excluded) in QA v1.5.0.67 and it seems fine now. No zero-byte files that should be folder.

**Comment by AlenPelin** [comment] 2017-06-07 03:13
@ivanbuzyka @SaintSkeeta please check last version (1.5.0.82) and confirm if it is fixed.

**Comment by ivanbuzyka** [comment] 2017-06-07 08:28
I confirm that importing works in the QA version now.
However, the export zip still contains those zero size files with no extensions (https://db.tt/Y5S34H1BFb). So I assume, the export cannot be imported into older SIM version

**Comment by SaintSkeeta** [comment] 2017-06-07 17:59
I'm seeing that too.
The export still has the 0 byte files (instead of folders).....but at least the import then imports them as folders.

So yeah....I don't think it would be backwards compatible.

**Comment by AlenPelin** [comment] 2017-10-24 00:48
Cannot reproduce via SIM QA 1.5.0.153

**Closed by AlenPelin** 2017-10-24 00:48 UTC
Labels: bug, duplicate
