### ISSUE TITLE
Old 6.x and 7.x versions can not be downloaded anymore

### ISSUE THREAD

**Issue by sebastiantecsi** [Sitecore/Sitecore-Instance-Manager#213] opened 2017-12-06 13:31 UTC
**Description:**  
Except Sitecore Versions 8.x and 9, the old 6.x and 7.x versions can not be downloaded.

I hereby confirm the issue is reproducible on the latest QA version 1.5.0.171
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Attachments:**  
Please find attached latest log files from this folders:
```
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Manager-QA\logs 
```
[2017-12-06.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1535290/2017-12-06.txt)
[2017-12-06_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1535291/2017-12-06_DEBUG.txt)

**Comment by AlenPelin** [comment] 2017-12-12 22:47
Thanks @sebastiantecsi for reporting the issue. Unfortunately it is by design, these releases are in extended support and not a mainstream anymore - so not needed for most people.

**Comment by AlenPelin** [comment] 2017-12-12 23:21
It seems downloading works well, however the result filename is wrong e.g. `Sitecore65rev12356.download`

**Comment by AlenPelin** [comment] 2017-12-12 23:24
I don't have time to research this now, so as a workaround 6.x and 7.x won't be supported anymore.

**Closed** 2017-12-12 23:25 UTC
